#!/bin/bash

# Written by Dino Rossegger
# License: MIT
# v0.1.0

action=$1
flag=$2
shift
editor='nvim'

[ "$action" = "usage" ] && {
  echo ""
  echo "    open "
  echo "      Show todo.txt in favorite editor"
  echo "      tickler   opens tickler.txt instead"
  echo ""
  exit
}
[ "$action" = "open" ] && [ "$#" = 0 ] && {
  $editor $TODO_FILE
}
[ "$action" = "open" ] && [ "$1" = "tickler" ] && {
  $editor $TICKLER_FILE
}
